---
title: Using RScript for R Installation Managment
author: Konrad Zdeb
date: '2022-01-03'
slug: rscript-for-r-managment
categories:
  - how-to
tags:
  - bash
  - R
---

Most frequently, users tend to undertake common R installation and management tasks from within the R session. On numerous occasions, users frequently make use of commands, like `install.packages`, `update.packages` or `old.packages` to obtain or update packages. Frequently, those common tasks are accomplished via the GUI offered within RStudio, which provides an effortless mechanism for undertaking those operations or when working through console. This is OK for vast majority of cases; however, there are some instances when working within REPL to accomplish common installation tasks is not as convenient as it could be. 

For example, we may be utilising multiple library paths and our intention may be to update only one of the available libraries. If our `.libPaths()` returns a content similar to the one below, we may be interested only in updating the first repository.

```{r lib_pathsi, eval=FALSE}
.libPaths()
# [1] "/Users/thisUserName/Library/R/4/library"
# [2] "/usr/local/Cellar/r/4.1.2/lib/R/library"
```
This can be achieved using `update.packages(lib.loc =  .libPaths()[1])` but if our intention is to pass more arguments to the call, this becomes more tedious and unnecessarily onerous, especially with frequent command execution. Python users will be familiar with Conda and pip and may be longing for a solution offering convenient command line mechanism facilitating installation of packages. For instance in Conda we would simply do `conda install package-name=2.3.4` to install a package of a specific version. Similarly we can simply run `conda update --all -y` to update all packages unprompted or pass further arguments to update packages within a specific environment and so forth. Pip offers a number of similar convenience features.

## "Requirements"

I was interested in obtaining a comparable level of convenience that I could utilise with my R installation. However, as R does not offer package management mechanism that would be out of the box accessible via command line. 

# Solution

R offers two interfaces for running scripts and commands without starting an interactive session: `R CMD` and `RScript`. `R CMD` is an older interface facilitating command and script execution via command line. 

## Updating Packages

In the process of updating packages we will be usually interested in achieving two goals:

* Identifying any outdated packages that may benefit from updating
* Running an update for outdated packages every so often. This is relatiely good habit, comparable to running `brew upgrade` with some frequency so we can avoid our production environment differentiating more from the current stable releases.

### Outdated packages

For a start, let's attempt to list the outdated packages using `Rscriipt`. This is achieved in the following manner

```{bash, engine.opts='-l'}
Rscript --no-save --no-restore --no-init-file -e 'as.data.frame(old.packages(repos = "https://cran.rstudio.com"))[,-c(1,6)]'
```

#### Explanation

`Rscript` can be run with multiple switches:

* `--no-init-file` skips reading of the `.Rprofile` files. As I keep my library path stored within the `Renviron` file, I'm skipping processing of the `.RProfile` file.
* `--no-save` prevents `RScript` from saving data


