theme: "hugo-PaperMod"
baseURL: https://konradzdeb.netlify.com/
languageCode: en-gb
googleAnalytics: "UA-129716792-1"
title: The Final Artefact
ignoreFiles: [
  "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"
]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20

params:
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: auto # to switch between dark or light according to browser theme
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    homeInfoParams:
        Title:  The Final Artefact
        Content: Yet another blog on coding and business
    socialIcons:
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/konradzdeb"
        - name: "GitHub"
          url: "https://github.com/konradzdeb"

markup:
  goldmark:
    renderer:
      unsafe: true
