[build]
command = "hugo --gc --minify --baseURL=https://thefinalartefact.blog/"
publish = "public"

[build.environment]
HUGO_VERSION = "0.148.1"

[context.production]
command = "hugo --gc --minify --baseURL=https://thefinalartefact.blog/"
[context.production.environment]
HUGO_ENV = "production"

# Make branch and preview builds use their own URL
[context.branch-deploy]
command = "hugo --gc --minify --baseURL=$DEPLOY_URL/"

[context.deploy-preview]
command = "hugo --gc --minify --baseURL=$DEPLOY_PRIME_URL/"
