[build]
command = "hugo --gc --minify --baseURL=https://thefinalartefact.blog"
publish = "public"
[build.environment]
HUGO_VERSION = "0.148.1"

[context]
[context.branch-deploy]
command = "hugo --gc --minify"
[context.deploy-preview]
command = "hugo --gc --minify"
[context.production]
command = "hugo --gc --minify --baseURL=https://thefinalartefact.blog"
[context.production.environment]
HUGO_ENV = "production"
