---
title: Sample Analytical App with Shiny
author: Konrad Zdeb
date: '2020-07-28'
slug: sample-analytical-app-with-shiny
categories:
  - dev
  - how-to
tags:
  - R
  - Shiny
  - package
  - production
---

# Introduction

This article draws on the past post concerned with utilisation of [`golem`](https://github.com/ThinkR-open/golem) for robust deployment of analytical and reporting solutions. For this article, we will assume that we are working with defined working requirements that utilise some of the Labour Market Statistics disseminated through the [*nomis*](https://www.nomisweb.co.uk) portal.

## Change Plan

**What we have**

 - Reporting requirements
 - Past scripts we used to create reports with accompanying instructions
 
**What we want**

 - *Stronger business continuity* - we want to be able to give some access to this project and don't be concerned with missing files, outdated unavailable documentation and questions on how to produce updated reports. We want self-encompassing entity that takes of care of its technical requirements and user-interaction^[Good parallel can be drawn between this approach and manuals available with life-saving equipment. Equipment delivers technical capacity and manual ensures operational capacity. In case of an inexperienced user one is not useful without the other. We want to ensure that user with minimum required capacity can use the tools correctly.]
 
 - *Better reproducibility* - Easier way to re-run reports on custom parameters
 
 - *Improved efficiency* - We want to have a possibility of quickly creating updated and re-running past reports using the app.
 
 - *Better development:*
   - We want to ensure that any change requests to our reporting/analytical stack won't break crucial functionalities.
   - We want to modularise development so new corporate branding or visualisation requirements can be applied with no (or minimal) integration in analytical function
   
# Development

## I. Framework

Future robust development owes a lot to solid foundations. For the ease of :wq



