---
title: Inserting Data into Partitioned Table
author: Konrad Zdeb
date: '2021-02-26'
slug: []
categories:
  - how-to
  - example
tags:
  - R
  - Spark
references:
- id: costa2019
  title: Evaluating partitioning and bucketing strategies for Hive‐based Big Data Warehousing systems
  author:
  - family: Costa
    given: Eduarda
  - family: Costa
    given: Carlos
  - family: Santos
    given: Maribel Yasmina
  container-title: Journal of Big Data
  volume: 6
  URL: 'https://doi.org/10.1186/s40537-019-0196-1'
  DOI: 10.1186/s40537-019-0196-1
  issue: 34
  publisher: Nature Publishing Group
  page: 1-38
  type: article-journal
  issued:
    year: 2019
    month: 4
---

# Rationale
Maintaining partitioned Hive tables is a frequent practice in a business. Properly structured tables are conducive to achieving robust performance through speeding up query execution [see @costa2019]. Frequent use cases pertain to creating tables with hierarchical partition structure. In context of a data that is refreshed daily, the frequently utilised partition structure reflects years, months and dates. 

## Creating partitioned table

In HiveQL we would create the table with the following structure using the syntax below. In order to keep the development tidy, I'm creating a separate database on Hive which I will use for the purpose of creating tables for this article.

```{sql, eval=FALSE}
-- Initially test database is created to keep the development tidy
CREATE DATABASE blog COMMENT 'Blog article samples, can be deleted.';
-- Example table is created
CREATE TABLE blog.sample_partitioned_table (
		value_column_a FLOAT 	COMMENT 'Column will hold 4-byte number', 
		value_column_b DOUBLE 	COMMENT '8-byte double precision', 
		value_column_c CHAR(1) 	COMMENT 'Fixed length varchar') 
	COMMENT 'Sample partitioned table stored as text file' 
	PARTITIONED BY (
		part_year SMALLINT 	COMMENT 'Data load year, partition', 
		part_month TINYINT 	COMMENT 'Data load month, partition',
		part_day TINYINT	COMMENT 'Data load day, partition')
	ROW FORMAT DELIMITED
	FIELDS TERMINATED BY '\t'
	LINES TERMINATED BY '\n'
	STORED AS TEXTFILE;
```
The code snippet above achieves the following:
 
- Table `sample_partitioned_table` is created within newly created database `blog`.
- Three value columns are defined of `FLOAT`, `DOUBLE` and `CHAR(1)` types. Hive offers fairly rich set of data types and it's worth to study [the official documentation](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types) in order to ensure that selection of types is optimal considering the data we want to feed into the table. 

# References
